name: Get GitHub Actions IP
# on:
#   workflow_dispatch:

on:
  push:
    branches:
      - main  # Change this to your main branch name
jobs:
  get_ip:
    runs-on: ubuntu-latest
    steps:
      - name: Get GitHub Actions IP
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Print IP Address
        run: echo "GitHub Actions IP address:${{ steps.ip.outputs.ipv4 }}"
